// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD59qkUmKYJnLMOAX3FiE2uF-1J8skdLvM',
    appId: '1:704032314768:web:3a54725d65a366748c0f15',
    messagingSenderId: '704032314768',
    projectId: 'misnotas-flutter-project-97783',
    authDomain: 'misnotas-flutter-project-97783.firebaseapp.com',
    storageBucket: 'misnotas-flutter-project-97783.appspot.com',
    measurementId: 'G-MHX3DTE4XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh7UuIDOP8QJXYTr7v7QKG75ZpaHVyBsE',
    appId: '1:704032314768:android:bc902e6d108b2f318c0f15',
    messagingSenderId: '704032314768',
    projectId: 'misnotas-flutter-project-97783',
    storageBucket: 'misnotas-flutter-project-97783.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5mfimCyuDxvtv5cTTUlQ08KXg2JUcXRg',
    appId: '1:704032314768:ios:9b0e2a787dfeaa378c0f15',
    messagingSenderId: '704032314768',
    projectId: 'misnotas-flutter-project-97783',
    storageBucket: 'misnotas-flutter-project-97783.appspot.com',
    iosClientId: '704032314768-t2ko40766hqlk0785tjgbu4uc0mobihq.apps.googleusercontent.com',
    iosBundleId: 'dev.brayancjr7.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5mfimCyuDxvtv5cTTUlQ08KXg2JUcXRg',
    appId: '1:704032314768:ios:9b0e2a787dfeaa378c0f15',
    messagingSenderId: '704032314768',
    projectId: 'misnotas-flutter-project-97783',
    storageBucket: 'misnotas-flutter-project-97783.appspot.com',
    iosClientId: '704032314768-t2ko40766hqlk0785tjgbu4uc0mobihq.apps.googleusercontent.com',
    iosBundleId: 'dev.brayancjr7.mynotes',
  );
}
